### ISSUE TITLE
IMAP Server with mysql?

### ISSUE THREAD

**Issue by ghost** [maxvyaznikov/imapseagull#6]
Hi,

i'm not sure whether this is the right way to contact you. I'm new with nodejs and want to use your imap server with mysql (not with mongo)... ist that possible?

in the next step i just want to handle using DRAFTs in a special folder that the client created. is that possible or could you help me please with this "little" project?

thanks a lot

**Comment by maxvyaznikov** [comment]
Hi. MySQL support didn't planned, but possible because of architecture design. You can use [this package] (https://github.com/maxvyaznikov/imapseagull-storage-mongo) to fork, rename to imapseagull-storage-mysql, for example, and implement MySQL support as you see it. I'll help you as I can.

**Comment by krzysztofantczak** [comment]
https://github.com/guscaplan/imapseagull-storage-mysql ;-)

**Comment by maxvyaznikov** [comment]
You are writing a MySQL adapter - it's great! But most of code is still for MongoDB only...

**Comment by krzysztofantczak** [comment]
It's not my code, i've just found it while poking around with google and 'imapseagull' ;-)
