### ISSUE TITLE
Collections structure?

### ISSUE THREAD

**Issue by izanagi1995** [maxvyaznikov/imapseagull#8]
Hello,

I'm very interested by your project. But I have one question : What is the required structure for the collections? I'm mean what is the structure for the message collection? Can I store a dump of a mail in a single field or store all attributes in separated fields?

**Comment by maxvyaznikov** [comment]
Hi, thanks for insterest. 
Current version of DB-structure based on separate fields for reasons of convenience. See these comments for details (for function MongoDecorator.prototype.parse_raw_msg) https://github.com/maxvyaznikov/imapseagull-storage-mongo/blob/master/index.js#L50-L69
It is theoretically can be changed in another "imapseagull-storage-<db-backend>". But I can't recommend you to do it, because of heaviness. 
Current version of imapseagull tested only with imapseagull-storage-mongo with separete fields and I can't tell what bugs will be in version with standart mail structure.

**Comment by izanagi1995** [comment]
Thank you!

**Comment by izanagi1995** [comment]
I've read your function but I have one more question : 
https://github.com/maxvyaznikov/imapseagull-storage-mongo/blob/master/index.js#L164-L180
This function can insert mail but what are all those args?

**Comment by maxvyaznikov** [comment]
I'm sorry, forgot about it. `parse_raw_msg` translate email to set of fields, but for fundamental IMAP-features, like FETCH (https://github.com/maxvyaznikov/imapseagull/blob/master/lib/commands/handlers/fetch.js), LIST (https://github.com/maxvyaznikov/imapseagull/blob/master/lib/commands/list.js) or SEARCH (https://github.com/maxvyaznikov/imapseagull/blob/master/lib/commands/handlers/search.js) there must be fields like:
`folder` (INBOX, Sent, Draft, etc) for FETCH, LIST and another like this, 
`user` (I used ObjectID for it and another collection `users`) also,
`flags` (\Seen, for example or custom user flags) also,
`date` and `internaldate` required for such functions like SEARCH,
`attached_files` not so required as other fields, just is in list =)

**Comment by maxvyaznikov** [comment]
Here is example from real system (myclerk.ru):
```
{  
   "_id":ObjectId("5453c700ad8fd6de1471bfd2"),
   "uid":2,
   "user":ObjectId("53999d8944ea281c39c4c61d"),
   "subject":null,
   "date":   ISODate("2014-10-31T17:29:25   Z"),
   "internaldate":   ISODate("2014-10-31T17:29:36.298   Z"),
   "headers":{  
      "received":[  
         "by mail-yk0-f179.google.com with SMTP id 131so3471659ykp.24 for <max@myclerk.ru>; Fri, 31 Oct 2014 10:29:33 -0700 (PDT)",
         <...>
      ],
      "x-received":[  
         "by 10.170.214.6 with SMTP id g6mr6753058ykf.34.1414776573490; Fri, 31 Oct 2014 10:29:33 -0700 (PDT)",
         <...>
      ],
      "x-forwarded-to":[  
         "max@myclerk.ru"
      ],
      "x-forwarded-for":"max@myclerk.ru",
      "delivered-to":[  
         <...>
      ],
      <...>
   },
   "text":"<...>",
   "html":null,
   "html_safe":"",
   "folder":"\\Inbox",
   "contact_from":{  
      "email":"<...>",
      "name":{  
         "first":"<...>",
         "last":"<...>"
      }
   },
   "contacts_to":[
   ],
   "to":[  
      {  
         "address":"<...>",
         "name":"<...>"
      }
   ],
   "attached_files":[  
      {  
         "path":"7c63baf11ecd5891a9a5d04c585d1f49-606889",
         "name":"<...>",
         "ext":"docx",
         "cid":"41b9ab23498a9dd752d97e50e5a72baf@mailparser",
         "length":58474,
         "contentType":"application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      }
   ],
   "flags":[  
      "\\Seen"
   ]
}
```

**Comment by izanagi1995** [comment]
Thank you! What is `contacts_to` and `contacts_from` ? :smiley:

**Comment by maxvyaznikov** [comment]
It's for UI to make life easier :-)

**Comment by maxvyaznikov** [comment]
...`html_safe` also for UI

**Comment by izanagi1995** [comment]
Thank you! It would be fine to add the minimal document to the README.md

**Comment by izanagi1995** [comment]
What is the uid field?

**Comment by maxvyaznikov** [comment]
It's an unique number for message. See https://tools.ietf.org/html/rfc3501#section-2.3.1.1 for details
