### ISSUE TITLE
toString('binary') is deprecated

### ISSUE THREAD

**Issue by WhyEvenTry** [maxvyaznikov/imapseagull#9]
I already opened a ticket for hoodiecrow but was curious if you had solved this conundrum and found that no, it's still the same code that uses this function that node.js API documentation warns not to use and that is going to be removed:

https://github.com/andris9/hoodiecrow/issues/19

**Comment by maxvyaznikov** [comment]
Thank you very much. I'll see!

**Comment by baudehlo** [comment]
I'm pretty sure they changed their mind about removing that, since it's
very useful.
